---
# Theming
font: Inter Display 24
background: "#faf4edf0"
color: "#575279"
border: "#907aa9"
separator: " âžœ "
border_width: 4
corner_r: 12
padding: 15 # Defaults to corner_r
rows_per_column: 8 # No limit by default
column_padding: 25 # Defaults to padding

anchor: center

menu:
  - key: space
    desc: Fuzzel
    cmd: fuzzel
  - key: Return
    desc: Terminal
    cmd: foot
  - key: backslash
    desc: 1Password
    cmd: 1password --quick-access
  - key: e
    desc: Email
    cmd: thunderbird

  - key: b
    desc: Browser
    submenu:
      - key: b
        desc: Firefox
        cmd: firefox
      - key: B
        desc: Brave
        cmd: brave

  - key: c
    desc: Chats
    submenu:
      - key: d
        desc: Discord
        cmd: discord
      - key: s
        desc: Signal
        cmd: signal-desktop
      - key: w
        desc: Slack
        cmd: slack
      - key: z
        desc: Zoom
        cmd: zoom

  - key: d
    desc: Development
    submenu:
      - key: c
        desc: Cursor
        cmd: code-cursor
      - key: d
        desc: LazyDocker
        cmd: lazydocker
      - key: n
        desc: NeoVim
        cmd: foot -e nvim

  - key: f
    desc: File Manager
    submenu:
      - key: n
        desc: Nautilus
        cmd: nautilus
      - key: y
        desc: Yazi
        cmd: foot -e yazi

  - key: g
    desc: Gaming
    submenu:
      - key: l
        desc: Lutris
        cmd: lutris
      - key: r
        desc: RetroArch
        cmd: retroarch
      - key: S
        desc: Steam
        cmd: steam

  - key: m
    desc: Media
    submenu:
      - key: a
        desc: Audacity
        cmd: audacity
      - key: b
        desc: Amberol
        cmd: amberol
      - key: c
        desc: coppwr
        cmd: coppwr
      - key: e
        desc: EasyEffects
        cmd: easyeffects
      - key: f
        desc: Feishin
        cmd: feishin
      - key: j
        desc: Jellyfin
        cmd: jellyfin-chromium
      - key: m
        desc: mpv
        cmd: mpv
      - key: n
        desc: Navidrome
        cmd: navidrome-chromium
      - key: p
        desc: Picard
        cmd: picard
      - key: q
        desc: qpwgraph
        cmd: qpwgraph
      - key: v
        desc: pwvucontrol
        cmd: pwvucontrol

  - key: n
    desc: Notes
    submenu:
      - key: d
        desc: Obsidian DNSimple
        cmd: xdg-open "obsidian://open?vault=DNSimple"
      - key: t
        desc: Today Journal
        cmd: foot -e ~/bin/today
      - key: v
        desc: Obsidian Vault
        cmd: xdg-open "obsidian://open?vault=Vault"

  - key: p
    desc: Power
    submenu:
      - key: "l"
        desc: "\U000F033E Lock"
        cmd: swaylock
      - key: "S"
        desc: "\U000F0425 Shutdown"
        cmd: systemctl poweroff
      - key: "R"
        desc: "\U000F0465 Reboot"
        cmd: systemctl reboot
      - key: "U"
        desc: "\U000F0904 S[u]spend"
        cmd: systemctl suspend
      - key: "O"
        desc: "\U000F0343 L[o]gout"
        cmd: niri msg action quit

  - key: r
    desc: Recording
    submenu:
      - key: f
        desc: Clip Firefox Audio
        cmd: ~/bin/clip_firefox
      - key: m
        desc: Clip mpv Audio
        cmd: ~/bin/clip_mpv
      - key: r
        desc: Record Screen
        cmd: ~/bin/record-screen
      - key: s
        desc: Screenshot
        cmd: ~/bin/screenshot

  - key: s
    desc: Streaming
    submenu:
      - key: c
        desc: StreamController
        cmd: streamcontroller
      - key: f
        desc: Firebot
        cmd: firebot
      - key: o
        desc: OBS
        cmd: obs
      - key: s
        desc: Start Streaming
        cmd: foot -e ~/bin/streaming_time
      - key: t
        desc: Twitch
        cmd: twitch-chromium
      - key: v
        desc: Veadotube Mini
        cmd: veadotube-mini

  - key: t
    desc: Tools
    submenu:
      - key: b
        desc: btop
        cmd: foot -e btop
      - key: c
        desc: Calculator
        cmd: gnome-calculator
      - key: d
        desc: Document Viewer
        cmd: papers
      - key: f
        desc: Font Viewer
        cmd: gnome-font-viewer
      - key: i
        desc: Photopea
        cmd: photopea-chromium
      - key: l
        desc: Loupe
        cmd: loupe
      - key: p
        desc: Pomodorolm
        cmd: pomodorolm
      - key: v
        desc: Video Trimmer
        cmd: video-trimmer
