---
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
undo_backspace: true
keyboard_layout: {layout: us, options: "ctrl:nocaps,altwin:menu_win"}
