[general]
output-filename = "~/Pictures/Screenshots/%Y-%m-%d-%H-%M-%S.png"
actions-on-escape = ["save-to-clipboard", "save-to-file", "exit"]
annotation-size-factor = 4
brush-smooth-history-size = 5
copy-command = "wl-copy"
corner-roundness = 12
initial-tool = "arrow"

[font]
family = "Inter"
style = "Bold"

[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
  "#ff1493",
  "#00ffff",
  "#a52a2a",
  "#dc143c",
  "#ffd700",
  "#008000",
]
